---
title: "Computing 4"
author: "Hoppenfeld"
date: "2/8/2018"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



## Augustin-Louis Cauchy

```{r  echo = FALSE}
rm(list=ls())
#library(broom)
#library(dplyr)
#library(tidyverse)
#library(magrittr)

set.seed(42069)

n=10000


x <- rnorm(n)

en <- rnorm(n)
ec <- rcauchy(n)


yn <- 0.8 + 0.3*x + en
yc <- 0.8 +0.3*x + ec

uniform <- runif(n= n)
simulation <- data.frame(x,yn,yc,en,ec, uniform)


```

```{r  include = FALSE}
#cauchy regression
  cauchy_001 <- cbind()
  cauchy_01 <- cbind()
  cauchy_1 <- cbind()
  cauchy_10 <- cbind()
  cauchy_100 <- cbind()

  normal_001 <- cbind()
  normal_01 <- cbind()
  normal_1 <- cbind()
  normal_10 <- cbind()
  normal_100 <- cbind()
  
  constant <- cbind()

  
  for (i in seq(10)){
   reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < .001)
  result <- coef(reg)[2]
  cauchy_001 <- rbind(cauchy_001 , result)

  reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < .01)
  result <- coef(reg)[2]
  cauchy_01 <- rbind(cauchy_01 , result)
  
  reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < .01)
  result <- coef(reg)[2]
  cauchy_1 <- rbind(cauchy_1 , result)
  
  reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < .10)
  result <- coef(reg)[2]
  cauchy_10 <- rbind(cauchy_10 , result)
  
  reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < 1)
  result <- coef(reg)[2]
  cauchy_100 <- rbind(cauchy_100 , result)
 
  
   reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < .001)
  result <- coef(reg)[2]
  normal_001 <- rbind(normal_001 , result)

  reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < .01)
  result <- coef(reg)[2]
  normal_01 <- rbind(normal_01 , result)
  
  reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < .01)
  result <- coef(reg)[2]
  normal_1 <- rbind(normal_1 , result)
  
  reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < .10)
  result <- coef(reg)[2]
  normal_10 <- rbind(normal_10 , result)
  
  reg <- lm(simulation$yc ~ simulation$x, subset = simulation$uniform < 1)
  result <- coef(reg)[2]
  normal_100 <- rbind(normal_100 , result)
  
  constant <- rbind(constant, 1)
 
  simulation$uniform <- runif(n= n)
 
}
  colnames(cauchy_001) <- "cauchy_001"
  colnames(cauchy_01) <- "cauchy_01"
  colnames(cauchy_1) <- "cauchy_1"
  colnames(cauchy_10) <- "cauchy_10"
  colnames(cauchy_100) <- "cauchy_100"
  
  colnames(normal_001) <- "normal_001"
  colnames(normal_01) <- "normal_01"
  colnames(normal_1) <- "normal_1"
  colnames(normal_10) <- "normal_10"
  colnames(normal_100) <- "normal_100"
 
   colnames(constant)  <- "constant"
  
results <- data.frame(cauchy_001, cauchy_01, cauchy_1, cauchy_10, cauchy_100, normal_001, normal_01, normal_1, normal_10, normal_100, constant)
result_mean <- aggregate(results, FUN = mean, by = list(results$constant))
result_sd <- aggregate(results, FUN = sd, by = list(results$constant))

stats <- rbind(result_mean, result_sd)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

